# This workflow is a pipeline of multiple actions ,it is   triggered  for commits and pull on master branch

name:  Publishing the Docker image

on:
  # triggered on push and pull_request on master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 
  build:
    # run the commands on ubuntu
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: geting the actor
        # getting the environment variable (the pseudo github of the actor)
        run: echo $GITHUB_ACTOR


      # verify that the repository  is under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
       
      - name: Build with maven
        run:  |
           cd  gamification-impl 
           mvn clean package
     
   
      - name: Building the Docker image
      
        run: |
           echo ${{ secrets.ATG }} | docker login ghcr.io -u ChickenLivesMatter --password-stdin

           cd  docker
           chmod 777 script_moveArtifact.sh
           ./script.sh
           docker build -t spring/gamification  .
           docker tag spring/gamification  ghcr.io/amteam-heig/gamification-Engine/spring/gamification:latest
           docker push ghcr.io/amteam-heig/gamification-Engine/spring/gamificationlatest


